baseURL = 'https://jakobfriedl.github.io/'
languageCode = 'en-us'
title = 'Home'
theme = 'monochrome'

# Navbar
[[menu.navbar]]
identifier = "about"
name = "About"
url = "/about/"
weight = 100
[[menu.navbar]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = -100
[[menu.navbar]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = -99

# Tags and Categories
[taxonomies]
category = "categories"

[outputs]
home = ["HTML", "RSS", "JSON"]