baseURL = 'https://jakobfriedl.github.io/'
languageCode = 'en-us'
title = 'Home'
theme = 'monochrome'

[params]
defaultContentLanguage = "en"
color_scheme = "dark"
capitalizeListTitles = false

enable_header_anchor = true

enable_toc = true
enable_collapsible_toc = true
enable_collapsible_changelogs = true

enable_site_search = true

# Global Footer
# footer = "Jakob Friedl © 2024"

# Navbar
[[menu.navbar]]
identifier = "about"
name = "About"
url = "/about/"
weight = 100
[[menu.navbar]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = -100
[[menu.navbar]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = -99

# Tags and Categories
[taxonomies]
category = "categories"

[outputs]
home = ["HTML", "RSS", "JSON"]