baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Jakob Friedl'
theme = 'monochrome'

[params]
defaultContentLanguage = "en"
color_scheme = "dark"

# Table of contents
enable_toc = true
enable_collapsible_toc = true
enable_collapsible_changelogs = true

# Footer
# footer = "Jakob Friedl © 2024"

enable_site_search = true

# Navbar
[[menu.navbar]]
identifier = "about"
name = "About"
url = "/about/"
weight = 100

[[menu.navbar]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = -100

[[menu.navbar]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = -99

[taxonomies]
category = "categories"

[outputs]
home = ["HTML", "RSS", "JSON"]

